### ISSUE TITLE
mysql 'type' option removed

### ISSUE THREAD

**Issue by mjhoy** [danchoi/vnews#2]
In the MySQL 5.5, the "type" option of the create table command is removed, replaced by "engine". A syntax error is raised if type is used.

I have a possible fix here:

https://github.com/mjhoy/vnews/commit/5ad332969

It seemed that I needed to specify the encoding as well, or else I got the error: "Specified key was too long; max key length is 1000 bytes"

**Comment by danchoi** [comment]
Thanks. I put in your patch in 0.4.5.
