### ISSUE TITLE
uninitialized constant error when importing OPML

### ISSUE THREAD

**Issue by mlsimpson** [danchoi/vnews#3]
Importing OPML file Downloads/google-reader-subscriptions.xml
/Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.5/lib/vnews/opml.rb:15:in `block in import': uninitialized constant Vnews::Opml::ThreadPool (NameError)
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/nokogiri-1.5.2/lib/nokogiri/xml/node_set.rb:239:in`block in each'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/nokogiri-1.5.2/lib/nokogiri/xml/node_set.rb:238:in `upto'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/nokogiri-1.5.2/lib/nokogiri/xml/node_set.rb:238:in`each'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.5/lib/vnews/opml.rb:14:in `each_slice'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.5/lib/vnews/opml.rb:14:in`import'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.5/lib/vnews.rb:72:in `start'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.5/bin/vnews:9:in`<top (required)>'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/bin/vnews:19:in `load'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/bin/vnews:19:in`<main>'

**Comment by danchoi** [comment]
Thanks for reporting this. Please update the vnews gem to version 0.4.6 and try again.

**Comment by mlsimpson** [comment]
wow that was fast.  works!  thank you so much.

**Comment by mlsimpson** [comment]
I got about halfway done importing somewhere around 1000 feeds (heh) wheN I found this:

http://www.futureofmusicbook.com/feed/ -> Found text/xml utf-8
/Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:762:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:762:in`open'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/timeout.rb:54:in`timeout'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:762:in`connect'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/net/http.rb:744:in`start'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:306:in `open_http'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:775:in`buffer_open'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:201:in`catch'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:146:in`open_uri'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:33:in`open'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews/feed.rb:14:in `get_feed'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews/feed.rb:33:in`fetch_feed'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews/opml.rb:19:in `block (3 levels) in import'
    from /Users/threv/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/timeout.rb:68:in`timeout'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews/opml.rb:17:in `block (2 levels) in import'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews/opml.rb:15:in`each'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews/opml.rb:15:in `block in import'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/nokogiri-1.5.2/lib/nokogiri/xml/node_set.rb:239:in`block in each'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/nokogiri-1.5.2/lib/nokogiri/xml/node_set.rb:238:in `upto'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/nokogiri-1.5.2/lib/nokogiri/xml/node_set.rb:238:in`each'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews/opml.rb:14:in `each_slice'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews/opml.rb:14:in`import'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/lib/vnews.rb:72:in `start'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/gems/vnews-0.4.6/bin/vnews:9:in`<top (required)>'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/bin/vnews:19:in `load'
    from /Users/threv/.rvm/gems/ruby-1.9.3-p125/bin/vnews:19:in`<main>'

**Comment by danchoi** [comment]
Can you check your OPML file for the item after http://www.futureofmusicbook.com/feed/ ? Maybe it's no longer a valid URL?

**Comment by mlsimpson** [comment]
I'm deleting the feeds where it has problem.  I'll let you know.  Thanks!
